# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 1040)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 741, 1041))
        self.tabWidget.setObjectName("tabWidget")
        self.Transform = QtWidgets.QWidget()
        self.Transform.setObjectName("Transform")
        self.JtoFChose = QtWidgets.QRadioButton(self.Transform)
        self.JtoFChose.setGeometry(QtCore.QRect(20, 40, 132, 22))
        self.JtoFChose.setChecked(True)
        self.JtoFChose.setObjectName("JtoFChose")
        self.FtoJChose = QtWidgets.QRadioButton(self.Transform)
        self.FtoJChose.setGeometry(QtCore.QRect(20, 200, 132, 22))
        self.FtoJChose.setObjectName("FtoJChose")
        self.JOutFIleTipU = QtWidgets.QLabel(self.Transform)
        self.JOutFIleTipU.setGeometry(QtCore.QRect(20, 70, 211, 18))
        self.JOutFIleTipU.setObjectName("JOutFIleTipU")
        self.JOutFilePickU = QtWidgets.QPushButton(self.Transform)
        self.JOutFilePickU.setGeometry(QtCore.QRect(620, 65, 112, 28))
        self.JOutFilePickU.setObjectName("JOutFilePickU")
        self.GFileTip = QtWidgets.QLabel(self.Transform)
        self.GFileTip.setGeometry(QtCore.QRect(20, 100, 191, 18))
        self.GFileTip.setObjectName("GFileTip")
        self.FWorkTipU = QtWidgets.QLabel(self.Transform)
        self.FWorkTipU.setGeometry(QtCore.QRect(20, 130, 221, 18))
        self.FWorkTipU.setObjectName("FWorkTipU")
        self.GFilePick = QtWidgets.QPushButton(self.Transform)
        self.GFilePick.setGeometry(QtCore.QRect(620, 95, 112, 28))
        self.GFilePick.setObjectName("GFilePick")
        self.FWorkPickU = QtWidgets.QPushButton(self.Transform)
        self.FWorkPickU.setGeometry(QtCore.QRect(620, 125, 112, 28))
        self.FWorkPickU.setObjectName("FWorkPickU")
        self.GenTip = QtWidgets.QLabel(self.Transform)
        self.GenTip.setGeometry(QtCore.QRect(220, 40, 311, 18))
        self.GenTip.setObjectName("GenTip")
        self.GenRate = QtWidgets.QLineEdit(self.Transform)
        self.GenRate.setGeometry(QtCore.QRect(550, 36, 141, 25))
        self.GenRate.setObjectName("GenRate")
        self.Sync = QtWidgets.QCheckBox(self.Transform)
        self.Sync.setGeometry(QtCore.QRect(35, 880, 141, 22))
        self.Sync.setChecked(True)
        self.Sync.setObjectName("Sync")
        self.JOutFIleTipD = QtWidgets.QLabel(self.Transform)
        self.JOutFIleTipD.setGeometry(QtCore.QRect(20, 230, 211, 18))
        self.JOutFIleTipD.setObjectName("JOutFIleTipD")
        self.JOutFilePickD = QtWidgets.QPushButton(self.Transform)
        self.JOutFilePickD.setGeometry(QtCore.QRect(620, 225, 112, 28))
        self.JOutFilePickD.setObjectName("JOutFilePickD")
        self.FWorkTipD = QtWidgets.QLabel(self.Transform)
        self.FWorkTipD.setGeometry(QtCore.QRect(20, 260, 221, 18))
        self.FWorkTipD.setObjectName("FWorkTipD")
        self.FWorkPickD = QtWidgets.QPushButton(self.Transform)
        self.FWorkPickD.setGeometry(QtCore.QRect(620, 255, 112, 28))
        self.FWorkPickD.setObjectName("FWorkPickD")
        self.RetractLen = QtWidgets.QComboBox(self.Transform)
        self.RetractLen.setGeometry(QtCore.QRect(280, 196, 99, 24))
        self.RetractLen.setEditable(False)
        self.RetractLen.setObjectName("RetractLen")
        self.RetractLen.addItem("")
        self.RetractLen.addItem("")
        self.RetractLen.addItem("")
        self.RetractLen.addItem("")
        self.RetractTip = QtWidgets.QLabel(self.Transform)
        self.RetractTip.setGeometry(QtCore.QRect(190, 200, 91, 18))
        self.RetractTip.setAlignment(QtCore.Qt.AlignCenter)
        self.RetractTip.setObjectName("RetractTip")
        self.GenCall = QtWidgets.QCheckBox(self.Transform)
        self.GenCall.setGeometry(QtCore.QRect(205, 880, 141, 22))
        self.GenCall.setChecked(True)
        self.GenCall.setObjectName("GenCall")
        self.FileEdit = QtWidgets.QTabWidget(self.Transform)
        self.FileEdit.setGeometry(QtCore.QRect(20, 360, 701, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileEdit.sizePolicy().hasHeightForWidth())
        self.FileEdit.setSizePolicy(sizePolicy)
        self.FileEdit.setObjectName("FileEdit")
        self.Collapx = QtWidgets.QWidget()
        self.Collapx.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Collapx.sizePolicy().hasHeightForWidth())
        self.Collapx.setSizePolicy(sizePolicy)
        self.Collapx.setObjectName("Collapx")
        self.CFileEdit = QtWidgets.QTextEdit(self.Collapx)
        self.CFileEdit.setEnabled(True)
        self.CFileEdit.setGeometry(QtCore.QRect(0, 0, 695, 260))
        self.CFileEdit.setAcceptRichText(False)
        self.CFileEdit.setPlaceholderText("")
        self.CFileEdit.setObjectName("CFileEdit")
        self.FileEdit.addTab(self.Collapx, "")
        self.Arrayx = QtWidgets.QWidget()
        self.Arrayx.setObjectName("Arrayx")
        self.AFileEdit = QtWidgets.QTextEdit(self.Arrayx)
        self.AFileEdit.setGeometry(QtCore.QRect(0, 0, 695, 260))
        self.AFileEdit.setAcceptRichText(False)
        self.AFileEdit.setObjectName("AFileEdit")
        self.FileEdit.addTab(self.Arrayx, "")
        self.Input = QtWidgets.QWidget()
        self.Input.setObjectName("Input")
        self.IFileEdit = QtWidgets.QTextEdit(self.Input)
        self.IFileEdit.setGeometry(QtCore.QRect(0, 0, 695, 260))
        self.IFileEdit.setOverwriteMode(True)
        self.IFileEdit.setTabStopWidth(77)
        self.IFileEdit.setAcceptRichText(False)
        self.IFileEdit.setPlaceholderText("")
        self.IFileEdit.setObjectName("IFileEdit")
        self.FileEdit.addTab(self.Input, "")
        self.Printlib = QtWidgets.QWidget()
        self.Printlib.setObjectName("Printlib")
        self.PFileEdit = QtWidgets.QTextEdit(self.Printlib)
        self.PFileEdit.setGeometry(QtCore.QRect(0, 0, 695, 260))
        self.PFileEdit.setOverwriteMode(True)
        self.PFileEdit.setTabStopWidth(77)
        self.PFileEdit.setAcceptRichText(False)
        self.PFileEdit.setPlaceholderText("")
        self.PFileEdit.setObjectName("PFileEdit")
        self.FileEdit.addTab(self.Printlib, "")
        self.JMCT = QtWidgets.QWidget()
        self.JMCT.setObjectName("JMCT")
        self.JFileEdit = QtWidgets.QTextEdit(self.JMCT)
        self.JFileEdit.setGeometry(QtCore.QRect(0, 0, 695, 260))
        self.JFileEdit.setAcceptRichText(False)
        self.JFileEdit.setObjectName("JFileEdit")
        self.FileEdit.addTab(self.JMCT, "")
        self.Bar = QtWidgets.QProgressBar(self.Transform)
        self.Bar.setGeometry(QtCore.QRect(22, 920, 691, 23))
        self.Bar.setProperty("value", 0)
        self.Bar.setAlignment(QtCore.Qt.AlignCenter)
        self.Bar.setTextVisible(True)
        self.Bar.setObjectName("Bar")
        self.StatusL = QtWidgets.QTextBrowser(self.Transform)
        self.StatusL.setGeometry(QtCore.QRect(23, 661, 695, 191))
        self.StatusL.setObjectName("StatusL")
        self.LoadFile = QtWidgets.QPushButton(self.Transform)
        self.LoadFile.setGeometry(QtCore.QRect(590, 340, 141, 34))
        self.LoadFile.setObjectName("LoadFile")
        self.StartL = QtWidgets.QPushButton(self.Transform)
        self.StartL.setGeometry(QtCore.QRect(559, 960, 112, 34))
        self.StartL.setObjectName("StartL")
        self.ResetL = QtWidgets.QPushButton(self.Transform)
        self.ResetL.setGeometry(QtCore.QRect(315, 960, 112, 34))
        self.ResetL.setObjectName("ResetL")
        self.QuitL = QtWidgets.QPushButton(self.Transform)
        self.QuitL.setGeometry(QtCore.QRect(70, 960, 112, 34))
        self.QuitL.setObjectName("QuitL")
        self.LineL = QtWidgets.QFrame(self.Transform)
        self.LineL.setGeometry(QtCore.QRect(6, 170, 721, 20))
        self.LineL.setFrameShape(QtWidgets.QFrame.HLine)
        self.LineL.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineL.setObjectName("LineL")
        self.MaxFlagTip = QtWidgets.QLabel(self.Transform)
        self.MaxFlagTip.setGeometry(QtCore.QRect(410, 200, 151, 18))
        self.MaxFlagTip.setObjectName("MaxFlagTip")
        self.MaxFlag = QtWidgets.QLineEdit(self.Transform)
        self.MaxFlag.setGeometry(QtCore.QRect(570, 196, 113, 25))
        self.MaxFlag.setPlaceholderText("")
        self.MaxFlag.setObjectName("MaxFlag")
        self.JOutFilePathU = QtWidgets.QLineEdit(self.Transform)
        self.JOutFilePathU.setGeometry(QtCore.QRect(235, 66, 370, 25))
        self.JOutFilePathU.setMouseTracking(True)
        self.JOutFilePathU.setObjectName("JOutFilePathU")
        self.GFilePath = QtWidgets.QLineEdit(self.Transform)
        self.GFilePath.setGeometry(QtCore.QRect(235, 96, 370, 25))
        self.GFilePath.setObjectName("GFilePath")
        self.FWorkPathU = QtWidgets.QLineEdit(self.Transform)
        self.FWorkPathU.setGeometry(QtCore.QRect(235, 126, 370, 25))
        self.FWorkPathU.setObjectName("FWorkPathU")
        self.JOutFilePathD = QtWidgets.QLineEdit(self.Transform)
        self.JOutFilePathD.setGeometry(QtCore.QRect(240, 226, 370, 25))
        self.JOutFilePathD.setReadOnly(False)
        self.JOutFilePathD.setObjectName("JOutFilePathD")
        self.FWorkPathD = QtWidgets.QLineEdit(self.Transform)
        self.FWorkPathD.setGeometry(QtCore.QRect(240, 256, 370, 25))
        self.FWorkPathD.setObjectName("FWorkPathD")
        self.JModelTip = QtWidgets.QLabel(self.Transform)
        self.JModelTip.setGeometry(QtCore.QRect(20, 290, 211, 18))
        self.JModelTip.setObjectName("JModelTip")
        self.JModelPath = QtWidgets.QLineEdit(self.Transform)
        self.JModelPath.setGeometry(QtCore.QRect(240, 286, 370, 25))
        self.JModelPath.setObjectName("JModelPath")
        self.JModelPick = QtWidgets.QPushButton(self.Transform)
        self.JModelPick.setGeometry(QtCore.QRect(620, 285, 112, 28))
        self.JModelPick.setObjectName("JModelPick")
        self.RemainJOut = QtWidgets.QCheckBox(self.Transform)
        self.RemainJOut.setGeometry(QtCore.QRect(545, 880, 141, 22))
        self.RemainJOut.setChecked(True)
        self.RemainJOut.setObjectName("RemainJOut")
        self.SaveNeu = QtWidgets.QCheckBox(self.Transform)
        self.SaveNeu.setGeometry(QtCore.QRect(375, 880, 151, 22))
        self.SaveNeu.setObjectName("SaveNeu")
        self.FileEdit.raise_()
        self.JtoFChose.raise_()
        self.FtoJChose.raise_()
        self.JOutFIleTipU.raise_()
        self.JOutFilePickU.raise_()
        self.GFileTip.raise_()
        self.FWorkTipU.raise_()
        self.GFilePick.raise_()
        self.FWorkPickU.raise_()
        self.GenTip.raise_()
        self.GenRate.raise_()
        self.Sync.raise_()
        self.JOutFIleTipD.raise_()
        self.JOutFilePickD.raise_()
        self.FWorkTipD.raise_()
        self.FWorkPickD.raise_()
        self.RetractLen.raise_()
        self.RetractTip.raise_()
        self.GenCall.raise_()
        self.Bar.raise_()
        self.StatusL.raise_()
        self.LoadFile.raise_()
        self.StartL.raise_()
        self.ResetL.raise_()
        self.QuitL.raise_()
        self.LineL.raise_()
        self.MaxFlagTip.raise_()
        self.MaxFlag.raise_()
        self.JOutFilePathU.raise_()
        self.GFilePath.raise_()
        self.FWorkPathU.raise_()
        self.JOutFilePathD.raise_()
        self.FWorkPathD.raise_()
        self.JModelTip.raise_()
        self.JModelPath.raise_()
        self.JModelPick.raise_()
        self.RemainJOut.raise_()
        self.SaveNeu.raise_()
        self.tabWidget.addTab(self.Transform, "")
        self.Call = QtWidgets.QWidget()
        self.Call.setObjectName("Call")
        self.CallFISP = QtWidgets.QRadioButton(self.Call)
        self.CallFISP.setGeometry(QtCore.QRect(20, 40, 132, 22))
        self.CallFISP.setChecked(True)
        self.CallFISP.setObjectName("CallFISP")
        self.Weight = QtWidgets.QComboBox(self.Call)
        self.Weight.setGeometry(QtCore.QRect(255, 79, 99, 24))
        self.Weight.setObjectName("Weight")
        self.Weight.addItem("")
        self.Weight.addItem("")
        self.Weight.addItem("")
        self.WeightTip = QtWidgets.QLabel(self.Call)
        self.WeightTip.setGeometry(QtCore.QRect(25, 82, 221, 18))
        self.WeightTip.setTextFormat(QtCore.Qt.AutoText)
        self.WeightTip.setObjectName("WeightTip")
        self.ParticleTip = QtWidgets.QLabel(self.Call)
        self.ParticleTip.setGeometry(QtCore.QRect(460, 82, 81, 18))
        self.ParticleTip.setObjectName("ParticleTip")
        self.Particle = QtWidgets.QComboBox(self.Call)
        self.Particle.setGeometry(QtCore.QRect(570, 79, 51, 24))
        self.Particle.setObjectName("Particle")
        self.Particle.addItem("")
        self.Particle.addItem("")
        self.Particle.addItem("")
        self.GroupTip = QtWidgets.QLabel(self.Call)
        self.GroupTip.setGeometry(QtCore.QRect(140, 42, 211, 18))
        self.GroupTip.setObjectName("GroupTip")
        self.Group = QtWidgets.QComboBox(self.Call)
        self.Group.setGeometry(QtCore.QRect(370, 39, 161, 24))
        self.Group.setObjectName("Group")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.FTip = QtWidgets.QLabel(self.Call)
        self.FTip.setGeometry(QtCore.QRect(20, 130, 151, 18))
        self.FTip.setObjectName("FTip")
        self.FPath = QtWidgets.QLineEdit(self.Call)
        self.FPath.setGeometry(QtCore.QRect(170, 127, 430, 26))
        self.FPath.setObjectName("FPath")
        self.FPick = QtWidgets.QPushButton(self.Call)
        self.FPick.setGeometry(QtCore.QRect(615, 123, 112, 34))
        self.FPick.setObjectName("FPick")
        self.UseEnv = QtWidgets.QCheckBox(self.Call)
        self.UseEnv.setGeometry(QtCore.QRect(35, 880, 151, 22))
        self.UseEnv.setObjectName("UseEnv")
        self.ETip = QtWidgets.QLabel(self.Call)
        self.ETip.setGeometry(QtCore.QRect(20, 180, 131, 18))
        self.ETip.setObjectName("ETip")
        self.EPath = QtWidgets.QLineEdit(self.Call)
        self.EPath.setGeometry(QtCore.QRect(170, 177, 430, 26))
        self.EPath.setObjectName("EPath")
        self.EPick = QtWidgets.QPushButton(self.Call)
        self.EPick.setGeometry(QtCore.QRect(615, 173, 112, 34))
        self.EPick.setObjectName("EPick")
        self.FWorkTipR = QtWidgets.QLabel(self.Call)
        self.FWorkTipR.setGeometry(QtCore.QRect(20, 230, 151, 18))
        self.FWorkTipR.setObjectName("FWorkTipR")
        self.FWorkPathR = QtWidgets.QLineEdit(self.Call)
        self.FWorkPathR.setGeometry(QtCore.QRect(170, 227, 430, 26))
        self.FWorkPathR.setObjectName("FWorkPathR")
        self.FWorkPick = QtWidgets.QPushButton(self.Call)
        self.FWorkPick.setGeometry(QtCore.QRect(615, 223, 112, 34))
        self.FWorkPick.setObjectName("FWorkPick")
        self.LineR = QtWidgets.QFrame(self.Call)
        self.LineR.setGeometry(QtCore.QRect(20, 300, 691, 20))
        self.LineR.setFrameShape(QtWidgets.QFrame.HLine)
        self.LineR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineR.setObjectName("LineR")
        self.QuitR = QtWidgets.QPushButton(self.Call)
        self.QuitR.setGeometry(QtCore.QRect(70, 960, 112, 34))
        self.QuitR.setObjectName("QuitR")
        self.ResetR = QtWidgets.QPushButton(self.Call)
        self.ResetR.setGeometry(QtCore.QRect(315, 960, 112, 34))
        self.ResetR.setObjectName("ResetR")
        self.StartR = QtWidgets.QPushButton(self.Call)
        self.StartR.setGeometry(QtCore.QRect(559, 960, 112, 34))
        self.StartR.setObjectName("StartR")
        self.CallJMCT = QtWidgets.QRadioButton(self.Call)
        self.CallJMCT.setGeometry(QtCore.QRect(20, 340, 132, 22))
        self.CallJMCT.setChecked(False)
        self.CallJMCT.setObjectName("CallJMCT")
        self.JTip = QtWidgets.QLabel(self.Call)
        self.JTip.setGeometry(QtCore.QRect(20, 390, 131, 18))
        self.JTip.setObjectName("JTip")
        self.JPath = QtWidgets.QLineEdit(self.Call)
        self.JPath.setGeometry(QtCore.QRect(180, 387, 430, 26))
        self.JPath.setObjectName("JPath")
        self.JPick = QtWidgets.QPushButton(self.Call)
        self.JPick.setGeometry(QtCore.QRect(620, 383, 112, 34))
        self.JPick.setObjectName("JPick")
        self.JInTip = QtWidgets.QLabel(self.Call)
        self.JInTip.setGeometry(QtCore.QRect(20, 440, 161, 18))
        self.JInTip.setObjectName("JInTip")
        self.JInPath = QtWidgets.QLineEdit(self.Call)
        self.JInPath.setGeometry(QtCore.QRect(180, 437, 430, 26))
        self.JInPath.setObjectName("JInPath")
        self.JInPick = QtWidgets.QPushButton(self.Call)
        self.JInPick.setGeometry(QtCore.QRect(620, 433, 112, 34))
        self.JInPick.setObjectName("JInPick")
        self.StatusR = QtWidgets.QTextBrowser(self.Call)
        self.StatusR.setGeometry(QtCore.QRect(23, 500, 695, 352))
        self.StatusR.setObjectName("StatusR")
        self.tabWidget.addTab(self.Call, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.FileEdit.setCurrentIndex(0)
        self.Group.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.JtoFChose.setText(_translate("MainWindow", "JMCTtoFISP"))
        self.FtoJChose.setText(_translate("MainWindow", "FISPtoJMCT"))
        self.JOutFIleTipU.setText(_translate("MainWindow", "JMCT输出文件位置(.out):"))
        self.JOutFilePickU.setText(_translate("MainWindow", "浏览"))
        self.GFileTip.setText(_translate("MainWindow", "GDML文件位置(.gdml):"))
        self.FWorkTipU.setText(_translate("MainWindow", "FISPACT工作目录(folder):"))
        self.GFilePick.setText(_translate("MainWindow", "浏览"))
        self.FWorkPickU.setText(_translate("MainWindow", "浏览"))
        self.GenTip.setText(_translate("MainWindow", "光子单位时间产额(小数/科学记数法):"))
        self.Sync.setText(_translate("MainWindow", "工作目录同步"))
        self.JOutFIleTipD.setText(_translate("MainWindow", "JMCT输出文件位置(.out):"))
        self.JOutFilePickD.setText(_translate("MainWindow", "浏览"))
        self.FWorkTipD.setText(_translate("MainWindow", "FISPACT工作目录(folder):"))
        self.FWorkPickD.setText(_translate("MainWindow", "浏览"))
        self.RetractLen.setCurrentText(_translate("MainWindow", "Space*3"))
        self.RetractLen.setItemText(0, _translate("MainWindow", "Space*3"))
        self.RetractLen.setItemText(1, _translate("MainWindow", "Space*2"))
        self.RetractLen.setItemText(2, _translate("MainWindow", "Space*4"))
        self.RetractLen.setItemText(3, _translate("MainWindow", "Tab"))
        self.RetractTip.setText(_translate("MainWindow", "文本缩进:"))
        self.GenCall.setText(_translate("MainWindow", "生成调用语句"))
        self.CFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MONITOR 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">COLLAPSE 175</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FISPACT</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* {title}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* END OF RUN</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Collapx), _translate("MainWindow", "collapx.i"))
        self.AFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MONITOR 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SPEK</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ENFA</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* {title}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TAPA</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FISPACT</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* WRITE DATA TO ARRAY FILE.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* END OF RUN</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Arrayx), _translate("MainWindow", "arrayx.i"))
        self.IFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NOHEAD</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MONITOR 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AINP</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FISPACT</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* {title}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DENSITY {density}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MASS {mass} {elements}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MIND 1.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">HALF</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">GRAPH 2 0 0 1 2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FLUX {flux}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ATOMS</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LEVEL 100 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TIME 1.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">HALF</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DOSE 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ATOMS</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NOSTABLE</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LEVEL 20 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FLUX 0.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ZERO</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TIME 1.0 HOURS ATOMS</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Input), _translate("MainWindow", "input.i"))
        self.PFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Printlib), _translate("MainWindow", "printlib.i"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.JMCT), _translate("MainWindow", "jmct"))
        self.LoadFile.setText(_translate("MainWindow", "导入模板文件"))
        self.StartL.setText(_translate("MainWindow", "开始"))
        self.ResetL.setText(_translate("MainWindow", "重置"))
        self.QuitL.setText(_translate("MainWindow", "退出"))
        self.MaxFlagTip.setText(_translate("MainWindow", "光谱无穷大等效值:"))
        self.MaxFlag.setText(_translate("MainWindow", "20.0"))
        self.JModelTip.setText(_translate("MainWindow", "JMCT模板文件位置(.in):"))
        self.JModelPick.setText(_translate("MainWindow", "浏览"))
        self.RemainJOut.setText(_translate("MainWindow", "保留JMCT模板"))
        self.SaveNeu.setText(_translate("MainWindow", "物质信息暂存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Transform), _translate("MainWindow", "文件转换"))
        self.CallFISP.setText(_translate("MainWindow", "CallFISP"))
        self.Weight.setItemText(0, _translate("MainWindow", "FLA/FLT"))
        self.Weight.setItemText(1, _translate("MainWindow", "FIS"))
        self.Weight.setItemText(2, _translate("MainWindow", "FUS"))
        self.WeightTip.setText(_translate("MainWindow", "权函数(weight function):"))
        self.ParticleTip.setText(_translate("MainWindow", "粒子类型:"))
        self.Particle.setItemText(0, _translate("MainWindow", "n"))
        self.Particle.setItemText(1, _translate("MainWindow", "p"))
        self.Particle.setItemText(2, _translate("MainWindow", "d"))
        self.GroupTip.setText(_translate("MainWindow", "能群(group-structures):"))
        self.Group.setItemText(0, _translate("MainWindow", "69(WIMS)"))
        self.Group.setItemText(1, _translate("MainWindow", "100(GAM-2)"))
        self.Group.setItemText(2, _translate("MainWindow", "172(XMAS)"))
        self.Group.setItemText(3, _translate("MainWindow", "175(VITAMIN-J)"))
        self.Group.setItemText(4, _translate("MainWindow", "211(VITAMIN-J+)"))
        self.Group.setItemText(5, _translate("MainWindow", "315(TRIPOLI)"))
        self.Group.setItemText(6, _translate("MainWindow", "351(TRIPOLI+)"))
        self.FTip.setText(_translate("MainWindow", "FISPACT安装目录:"))
        self.FPick.setText(_translate("MainWindow", "浏览"))
        self.UseEnv.setText(_translate("MainWindow", "使用环境变量"))
        self.ETip.setText(_translate("MainWindow", "EAF数据库目录:"))
        self.EPick.setText(_translate("MainWindow", "浏览"))
        self.FWorkTipR.setText(_translate("MainWindow", "FISPACT工作目录:"))
        self.FWorkPick.setText(_translate("MainWindow", "浏览"))
        self.QuitR.setText(_translate("MainWindow", "退出"))
        self.ResetR.setText(_translate("MainWindow", "重置"))
        self.StartR.setText(_translate("MainWindow", "开始"))
        self.CallJMCT.setText(_translate("MainWindow", "CallJMCT"))
        self.JTip.setText(_translate("MainWindow", "JMCT安装目录:"))
        self.JPick.setText(_translate("MainWindow", "浏览"))
        self.JInTip.setText(_translate("MainWindow", "JMCT输入文件(.in):"))
        self.JInPick.setText(_translate("MainWindow", "浏览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Call), _translate("MainWindow", "程序调用"))

