# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 1040)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Transform = QtWidgets.QWidget()
        self.Transform.setObjectName("Transform")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Transform)
        self.verticalLayout_7.setContentsMargins(13, -1, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LeftUpF1 = QtWidgets.QVBoxLayout()
        self.LeftUpF1.setObjectName("LeftUpF1")
        self.LeftUpS1 = QtWidgets.QHBoxLayout()
        self.LeftUpS1.setContentsMargins(10, -1, 10, -1)
        self.LeftUpS1.setSpacing(14)
        self.LeftUpS1.setObjectName("LeftUpS1")
        self.JtoFChose = QtWidgets.QRadioButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JtoFChose.sizePolicy().hasHeightForWidth())
        self.JtoFChose.setSizePolicy(sizePolicy)
        self.JtoFChose.setMinimumSize(QtCore.QSize(0, 32))
        self.JtoFChose.setChecked(True)
        self.JtoFChose.setObjectName("JtoFChose")
        self.LeftUpS1.addWidget(self.JtoFChose)
        self.LeftUpT1 = QtWidgets.QHBoxLayout()
        self.LeftUpT1.setContentsMargins(110, 5, 15, 5)
        self.LeftUpT1.setObjectName("LeftUpT1")
        self.GenTip = QtWidgets.QLabel(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GenTip.sizePolicy().hasHeightForWidth())
        self.GenTip.setSizePolicy(sizePolicy)
        self.GenTip.setObjectName("GenTip")
        self.LeftUpT1.addWidget(self.GenTip)
        self.GenRate = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GenRate.sizePolicy().hasHeightForWidth())
        self.GenRate.setSizePolicy(sizePolicy)
        self.GenRate.setObjectName("GenRate")
        self.LeftUpT1.addWidget(self.GenRate)
        self.LeftUpS1.addLayout(self.LeftUpT1)
        self.LeftUpF1.addLayout(self.LeftUpS1)
        self.LeftUpS2 = QtWidgets.QHBoxLayout()
        self.LeftUpS2.setContentsMargins(15, -1, 15, -1)
        self.LeftUpS2.setObjectName("LeftUpS2")
        self.JOutFIleTipU = QtWidgets.QLabel(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JOutFIleTipU.sizePolicy().hasHeightForWidth())
        self.JOutFIleTipU.setSizePolicy(sizePolicy)
        self.JOutFIleTipU.setMinimumSize(QtCore.QSize(0, 32))
        self.JOutFIleTipU.setObjectName("JOutFIleTipU")
        self.LeftUpS2.addWidget(self.JOutFIleTipU)
        self.JOutFilePathU = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JOutFilePathU.sizePolicy().hasHeightForWidth())
        self.JOutFilePathU.setSizePolicy(sizePolicy)
        self.JOutFilePathU.setMouseTracking(True)
        self.JOutFilePathU.setObjectName("JOutFilePathU")
        self.LeftUpS2.addWidget(self.JOutFilePathU)
        self.JOutFilePickU = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JOutFilePickU.sizePolicy().hasHeightForWidth())
        self.JOutFilePickU.setSizePolicy(sizePolicy)
        self.JOutFilePickU.setMaximumSize(QtCore.QSize(112, 34))
        self.JOutFilePickU.setObjectName("JOutFilePickU")
        self.LeftUpS2.addWidget(self.JOutFilePickU)
        self.LeftUpF1.addLayout(self.LeftUpS2)
        self.LeftUpS3 = QtWidgets.QHBoxLayout()
        self.LeftUpS3.setContentsMargins(15, 0, 15, 0)
        self.LeftUpS3.setObjectName("LeftUpS3")
        self.GFileTip = QtWidgets.QLabel(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GFileTip.sizePolicy().hasHeightForWidth())
        self.GFileTip.setSizePolicy(sizePolicy)
        self.GFileTip.setMinimumSize(QtCore.QSize(0, 32))
        self.GFileTip.setObjectName("GFileTip")
        self.LeftUpS3.addWidget(self.GFileTip)
        self.GFilePath = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GFilePath.sizePolicy().hasHeightForWidth())
        self.GFilePath.setSizePolicy(sizePolicy)
        self.GFilePath.setObjectName("GFilePath")
        self.LeftUpS3.addWidget(self.GFilePath)
        self.GFilePick = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GFilePick.sizePolicy().hasHeightForWidth())
        self.GFilePick.setSizePolicy(sizePolicy)
        self.GFilePick.setMaximumSize(QtCore.QSize(112, 34))
        self.GFilePick.setObjectName("GFilePick")
        self.LeftUpS3.addWidget(self.GFilePick)
        self.LeftUpF1.addLayout(self.LeftUpS3)
        self.LeftUpS4 = QtWidgets.QHBoxLayout()
        self.LeftUpS4.setContentsMargins(15, -1, 15, -1)
        self.LeftUpS4.setObjectName("LeftUpS4")
        self.FWorkTipU = QtWidgets.QLabel(self.Transform)
        self.FWorkTipU.setMinimumSize(QtCore.QSize(0, 32))
        self.FWorkTipU.setObjectName("FWorkTipU")
        self.LeftUpS4.addWidget(self.FWorkTipU)
        self.FWorkPathU = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWorkPathU.sizePolicy().hasHeightForWidth())
        self.FWorkPathU.setSizePolicy(sizePolicy)
        self.FWorkPathU.setObjectName("FWorkPathU")
        self.LeftUpS4.addWidget(self.FWorkPathU)
        self.FWorkPickU = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWorkPickU.sizePolicy().hasHeightForWidth())
        self.FWorkPickU.setSizePolicy(sizePolicy)
        self.FWorkPickU.setMaximumSize(QtCore.QSize(112, 34))
        self.FWorkPickU.setObjectName("FWorkPickU")
        self.LeftUpS4.addWidget(self.FWorkPickU)
        self.LeftUpF1.addLayout(self.LeftUpS4)
        self.LineL = QtWidgets.QFrame(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineL.sizePolicy().hasHeightForWidth())
        self.LineL.setSizePolicy(sizePolicy)
        self.LineL.setFrameShape(QtWidgets.QFrame.HLine)
        self.LineL.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineL.setObjectName("LineL")
        self.LeftUpF1.addWidget(self.LineL)
        self.LeftUpS5 = QtWidgets.QHBoxLayout()
        self.LeftUpS5.setObjectName("LeftUpS5")
        self.FtoJChose = QtWidgets.QRadioButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FtoJChose.sizePolicy().hasHeightForWidth())
        self.FtoJChose.setSizePolicy(sizePolicy)
        self.FtoJChose.setMinimumSize(QtCore.QSize(0, 32))
        self.FtoJChose.setObjectName("FtoJChose")
        self.LeftUpS5.addWidget(self.FtoJChose)
        self.LeftUpT2 = QtWidgets.QHBoxLayout()
        self.LeftUpT2.setContentsMargins(50, -1, -1, -1)
        self.LeftUpT2.setObjectName("LeftUpT2")
        self.RetractTip = QtWidgets.QLabel(self.Transform)
        self.RetractTip.setAlignment(QtCore.Qt.AlignCenter)
        self.RetractTip.setObjectName("RetractTip")
        self.LeftUpT2.addWidget(self.RetractTip)
        self.RetractLen = QtWidgets.QComboBox(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RetractLen.sizePolicy().hasHeightForWidth())
        self.RetractLen.setSizePolicy(sizePolicy)
        self.RetractLen.setEditable(False)
        self.RetractLen.setObjectName("RetractLen")
        self.RetractLen.addItem("")
        self.RetractLen.addItem("")
        self.RetractLen.addItem("")
        self.RetractLen.addItem("")
        self.LeftUpT2.addWidget(self.RetractLen)
        self.LeftUpL1 = QtWidgets.QHBoxLayout()
        self.LeftUpL1.setContentsMargins(50, -1, 15, -1)
        self.LeftUpL1.setObjectName("LeftUpL1")
        self.MaxFlagTip = QtWidgets.QLabel(self.Transform)
        self.MaxFlagTip.setObjectName("MaxFlagTip")
        self.LeftUpL1.addWidget(self.MaxFlagTip)
        self.MaxFlag = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxFlag.sizePolicy().hasHeightForWidth())
        self.MaxFlag.setSizePolicy(sizePolicy)
        self.MaxFlag.setPlaceholderText("")
        self.MaxFlag.setObjectName("MaxFlag")
        self.LeftUpL1.addWidget(self.MaxFlag)
        self.LeftUpT2.addLayout(self.LeftUpL1)
        self.LeftUpS5.addLayout(self.LeftUpT2)
        self.LeftUpF1.addLayout(self.LeftUpS5)
        self.LeftUpS6 = QtWidgets.QHBoxLayout()
        self.LeftUpS6.setContentsMargins(15, -1, 15, -1)
        self.LeftUpS6.setObjectName("LeftUpS6")
        self.JModelTip = QtWidgets.QLabel(self.Transform)
        self.JModelTip.setObjectName("JModelTip")
        self.LeftUpS6.addWidget(self.JModelTip)
        self.JModelPath = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JModelPath.sizePolicy().hasHeightForWidth())
        self.JModelPath.setSizePolicy(sizePolicy)
        self.JModelPath.setObjectName("JModelPath")
        self.LeftUpS6.addWidget(self.JModelPath)
        self.JModelPick = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JModelPick.sizePolicy().hasHeightForWidth())
        self.JModelPick.setSizePolicy(sizePolicy)
        self.JModelPick.setMaximumSize(QtCore.QSize(112, 34))
        self.JModelPick.setObjectName("JModelPick")
        self.LeftUpS6.addWidget(self.JModelPick)
        self.LeftUpF1.addLayout(self.LeftUpS6)
        self.LeftUpS7 = QtWidgets.QHBoxLayout()
        self.LeftUpS7.setContentsMargins(15, -1, 15, -1)
        self.LeftUpS7.setObjectName("LeftUpS7")
        self.FWorkTipD = QtWidgets.QLabel(self.Transform)
        self.FWorkTipD.setObjectName("FWorkTipD")
        self.LeftUpS7.addWidget(self.FWorkTipD)
        self.FWorkPathD = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWorkPathD.sizePolicy().hasHeightForWidth())
        self.FWorkPathD.setSizePolicy(sizePolicy)
        self.FWorkPathD.setObjectName("FWorkPathD")
        self.LeftUpS7.addWidget(self.FWorkPathD)
        self.FWorkPickD = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWorkPickD.sizePolicy().hasHeightForWidth())
        self.FWorkPickD.setSizePolicy(sizePolicy)
        self.FWorkPickD.setMaximumSize(QtCore.QSize(112, 34))
        self.FWorkPickD.setObjectName("FWorkPickD")
        self.LeftUpS7.addWidget(self.FWorkPickD)
        self.LeftUpF1.addLayout(self.LeftUpS7)
        self.LeftUpS8 = QtWidgets.QHBoxLayout()
        self.LeftUpS8.setContentsMargins(15, -1, 15, -1)
        self.LeftUpS8.setObjectName("LeftUpS8")
        self.JOutFIleTipD = QtWidgets.QLabel(self.Transform)
        self.JOutFIleTipD.setObjectName("JOutFIleTipD")
        self.LeftUpS8.addWidget(self.JOutFIleTipD)
        self.JOutFilePathD = QtWidgets.QLineEdit(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JOutFilePathD.sizePolicy().hasHeightForWidth())
        self.JOutFilePathD.setSizePolicy(sizePolicy)
        self.JOutFilePathD.setReadOnly(False)
        self.JOutFilePathD.setObjectName("JOutFilePathD")
        self.LeftUpS8.addWidget(self.JOutFilePathD)
        self.JOutFilePickD = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JOutFilePickD.sizePolicy().hasHeightForWidth())
        self.JOutFilePickD.setSizePolicy(sizePolicy)
        self.JOutFilePickD.setMaximumSize(QtCore.QSize(112, 34))
        self.JOutFilePickD.setObjectName("JOutFilePickD")
        self.LeftUpS8.addWidget(self.JOutFilePickD)
        self.LeftUpF1.addLayout(self.LeftUpS8)
        self.LeftUpS9 = QtWidgets.QHBoxLayout()
        self.LeftUpS9.setContentsMargins(-1, 5, 30, -1)
        self.LeftUpS9.setObjectName("LeftUpS9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LeftUpS9.addItem(spacerItem)
        self.LoadFile = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadFile.sizePolicy().hasHeightForWidth())
        self.LoadFile.setSizePolicy(sizePolicy)
        self.LoadFile.setMaximumSize(QtCore.QSize(119, 34))
        self.LoadFile.setObjectName("LoadFile")
        self.LeftUpS9.addWidget(self.LoadFile)
        self.LeftUpF1.addLayout(self.LeftUpS9)
        self.verticalLayout_7.addLayout(self.LeftUpF1)
        self.FileEdit = QtWidgets.QTabWidget(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileEdit.sizePolicy().hasHeightForWidth())
        self.FileEdit.setSizePolicy(sizePolicy)
        self.FileEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.FileEdit.setObjectName("FileEdit")
        self.Collapx = QtWidgets.QWidget()
        self.Collapx.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Collapx.sizePolicy().hasHeightForWidth())
        self.Collapx.setSizePolicy(sizePolicy)
        self.Collapx.setObjectName("Collapx")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Collapx)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CFileEdit = QtWidgets.QTextEdit(self.Collapx)
        self.CFileEdit.setEnabled(True)
        self.CFileEdit.setAcceptRichText(False)
        self.CFileEdit.setPlaceholderText("")
        self.CFileEdit.setObjectName("CFileEdit")
        self.verticalLayout_2.addWidget(self.CFileEdit)
        self.FileEdit.addTab(self.Collapx, "")
        self.Arrayx = QtWidgets.QWidget()
        self.Arrayx.setObjectName("Arrayx")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Arrayx)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.AFileEdit = QtWidgets.QTextEdit(self.Arrayx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AFileEdit.sizePolicy().hasHeightForWidth())
        self.AFileEdit.setSizePolicy(sizePolicy)
        self.AFileEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.AFileEdit.setAcceptRichText(False)
        self.AFileEdit.setObjectName("AFileEdit")
        self.verticalLayout_3.addWidget(self.AFileEdit)
        self.FileEdit.addTab(self.Arrayx, "")
        self.Input = QtWidgets.QWidget()
        self.Input.setObjectName("Input")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Input)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.IFileEdit = QtWidgets.QTextEdit(self.Input)
        self.IFileEdit.setOverwriteMode(True)
        self.IFileEdit.setTabStopWidth(77)
        self.IFileEdit.setAcceptRichText(False)
        self.IFileEdit.setPlaceholderText("")
        self.IFileEdit.setObjectName("IFileEdit")
        self.verticalLayout_4.addWidget(self.IFileEdit)
        self.FileEdit.addTab(self.Input, "")
        self.Printlib = QtWidgets.QWidget()
        self.Printlib.setObjectName("Printlib")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Printlib)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PFileEdit = QtWidgets.QTextEdit(self.Printlib)
        self.PFileEdit.setOverwriteMode(True)
        self.PFileEdit.setTabStopWidth(77)
        self.PFileEdit.setAcceptRichText(False)
        self.PFileEdit.setPlaceholderText("")
        self.PFileEdit.setObjectName("PFileEdit")
        self.verticalLayout_5.addWidget(self.PFileEdit)
        self.FileEdit.addTab(self.Printlib, "")
        self.JMCT = QtWidgets.QWidget()
        self.JMCT.setObjectName("JMCT")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.JMCT)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.JFileEdit = QtWidgets.QTextEdit(self.JMCT)
        self.JFileEdit.setAcceptRichText(False)
        self.JFileEdit.setObjectName("JFileEdit")
        self.verticalLayout_6.addWidget(self.JFileEdit)
        self.FileEdit.addTab(self.JMCT, "")
        self.verticalLayout_7.addWidget(self.FileEdit)
        self.StatusL = QtWidgets.QTextBrowser(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusL.sizePolicy().hasHeightForWidth())
        self.StatusL.setSizePolicy(sizePolicy)
        self.StatusL.setObjectName("StatusL")
        self.verticalLayout_7.addWidget(self.StatusL)
        self.LeftDown1 = QtWidgets.QHBoxLayout()
        self.LeftDown1.setContentsMargins(25, -1, -1, -1)
        self.LeftDown1.setObjectName("LeftDown1")
        self.Sync = QtWidgets.QCheckBox(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sync.sizePolicy().hasHeightForWidth())
        self.Sync.setSizePolicy(sizePolicy)
        self.Sync.setMaximumSize(QtCore.QSize(190, 32))
        self.Sync.setChecked(True)
        self.Sync.setObjectName("Sync")
        self.LeftDown1.addWidget(self.Sync)
        self.GenCall = QtWidgets.QCheckBox(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GenCall.sizePolicy().hasHeightForWidth())
        self.GenCall.setSizePolicy(sizePolicy)
        self.GenCall.setMinimumSize(QtCore.QSize(0, 32))
        self.GenCall.setMaximumSize(QtCore.QSize(190, 32))
        self.GenCall.setChecked(True)
        self.GenCall.setObjectName("GenCall")
        self.LeftDown1.addWidget(self.GenCall)
        self.SaveNeu = QtWidgets.QCheckBox(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveNeu.sizePolicy().hasHeightForWidth())
        self.SaveNeu.setSizePolicy(sizePolicy)
        self.SaveNeu.setMaximumSize(QtCore.QSize(190, 32))
        self.SaveNeu.setObjectName("SaveNeu")
        self.LeftDown1.addWidget(self.SaveNeu)
        self.RemainJOut = QtWidgets.QCheckBox(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemainJOut.sizePolicy().hasHeightForWidth())
        self.RemainJOut.setSizePolicy(sizePolicy)
        self.RemainJOut.setMaximumSize(QtCore.QSize(190, 32))
        self.RemainJOut.setChecked(True)
        self.RemainJOut.setObjectName("RemainJOut")
        self.LeftDown1.addWidget(self.RemainJOut)
        self.verticalLayout_7.addLayout(self.LeftDown1)
        self.Bar = QtWidgets.QProgressBar(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bar.sizePolicy().hasHeightForWidth())
        self.Bar.setSizePolicy(sizePolicy)
        self.Bar.setMaximumSize(QtCore.QSize(114514, 26))
        self.Bar.setBaseSize(QtCore.QSize(0, 0))
        self.Bar.setProperty("value", 0)
        self.Bar.setAlignment(QtCore.Qt.AlignCenter)
        self.Bar.setTextVisible(True)
        self.Bar.setObjectName("Bar")
        self.verticalLayout_7.addWidget(self.Bar)
        self.LeftDown2 = QtWidgets.QHBoxLayout()
        self.LeftDown2.setContentsMargins(70, 5, 70, 5)
        self.LeftDown2.setSpacing(70)
        self.LeftDown2.setObjectName("LeftDown2")
        self.QuitL = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuitL.sizePolicy().hasHeightForWidth())
        self.QuitL.setSizePolicy(sizePolicy)
        self.QuitL.setMaximumSize(QtCore.QSize(112, 34))
        self.QuitL.setObjectName("QuitL")
        self.LeftDown2.addWidget(self.QuitL)
        self.ResetL = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetL.sizePolicy().hasHeightForWidth())
        self.ResetL.setSizePolicy(sizePolicy)
        self.ResetL.setMaximumSize(QtCore.QSize(112, 34))
        self.ResetL.setObjectName("ResetL")
        self.LeftDown2.addWidget(self.ResetL)
        self.StartL = QtWidgets.QPushButton(self.Transform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartL.sizePolicy().hasHeightForWidth())
        self.StartL.setSizePolicy(sizePolicy)
        self.StartL.setMaximumSize(QtCore.QSize(112, 34))
        self.StartL.setObjectName("StartL")
        self.LeftDown2.addWidget(self.StartL)
        self.verticalLayout_7.addLayout(self.LeftDown2)
        self.tabWidget.addTab(self.Transform, "")
        self.Call = QtWidgets.QWidget()
        self.Call.setObjectName("Call")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Call)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.RightUp1 = QtWidgets.QHBoxLayout()
        self.RightUp1.setContentsMargins(10, -1, 15, -1)
        self.RightUp1.setObjectName("RightUp1")
        self.CallFISP = QtWidgets.QRadioButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CallFISP.sizePolicy().hasHeightForWidth())
        self.CallFISP.setSizePolicy(sizePolicy)
        self.CallFISP.setMinimumSize(QtCore.QSize(0, 40))
        self.CallFISP.setChecked(True)
        self.CallFISP.setObjectName("CallFISP")
        self.RightUp1.addWidget(self.CallFISP)
        self.GroupTip = QtWidgets.QLabel(self.Call)
        self.GroupTip.setObjectName("GroupTip")
        self.RightUp1.addWidget(self.GroupTip)
        self.Group = QtWidgets.QComboBox(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group.sizePolicy().hasHeightForWidth())
        self.Group.setSizePolicy(sizePolicy)
        self.Group.setObjectName("Group")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.Group.addItem("")
        self.RightUp1.addWidget(self.Group)
        self.verticalLayout_8.addLayout(self.RightUp1)
        self.RightUpF2 = QtWidgets.QHBoxLayout()
        self.RightUpF2.setContentsMargins(60, -1, 60, -1)
        self.RightUpF2.setSpacing(60)
        self.RightUpF2.setObjectName("RightUpF2")
        self.RightUpS1 = QtWidgets.QHBoxLayout()
        self.RightUpS1.setObjectName("RightUpS1")
        self.WeightTip = QtWidgets.QLabel(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WeightTip.sizePolicy().hasHeightForWidth())
        self.WeightTip.setSizePolicy(sizePolicy)
        self.WeightTip.setMinimumSize(QtCore.QSize(0, 40))
        self.WeightTip.setTextFormat(QtCore.Qt.AutoText)
        self.WeightTip.setObjectName("WeightTip")
        self.RightUpS1.addWidget(self.WeightTip)
        self.Weight = QtWidgets.QComboBox(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Weight.sizePolicy().hasHeightForWidth())
        self.Weight.setSizePolicy(sizePolicy)
        self.Weight.setObjectName("Weight")
        self.Weight.addItem("")
        self.Weight.addItem("")
        self.Weight.addItem("")
        self.RightUpS1.addWidget(self.Weight)
        self.RightUpF2.addLayout(self.RightUpS1)
        self.RightUpS2 = QtWidgets.QHBoxLayout()
        self.RightUpS2.setObjectName("RightUpS2")
        self.ParticleTip = QtWidgets.QLabel(self.Call)
        self.ParticleTip.setObjectName("ParticleTip")
        self.RightUpS2.addWidget(self.ParticleTip)
        self.Particle = QtWidgets.QComboBox(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Particle.sizePolicy().hasHeightForWidth())
        self.Particle.setSizePolicy(sizePolicy)
        self.Particle.setObjectName("Particle")
        self.Particle.addItem("")
        self.Particle.addItem("")
        self.Particle.addItem("")
        self.RightUpS2.addWidget(self.Particle)
        self.RightUpF2.addLayout(self.RightUpS2)
        self.verticalLayout_8.addLayout(self.RightUpF2)
        self.RightUp3 = QtWidgets.QHBoxLayout()
        self.RightUp3.setContentsMargins(15, 5, 15, 5)
        self.RightUp3.setObjectName("RightUp3")
        self.FTip = QtWidgets.QLabel(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FTip.sizePolicy().hasHeightForWidth())
        self.FTip.setSizePolicy(sizePolicy)
        self.FTip.setMinimumSize(QtCore.QSize(0, 40))
        self.FTip.setObjectName("FTip")
        self.RightUp3.addWidget(self.FTip)
        self.FPath = QtWidgets.QLineEdit(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPath.sizePolicy().hasHeightForWidth())
        self.FPath.setSizePolicy(sizePolicy)
        self.FPath.setObjectName("FPath")
        self.RightUp3.addWidget(self.FPath)
        self.FPick = QtWidgets.QPushButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPick.sizePolicy().hasHeightForWidth())
        self.FPick.setSizePolicy(sizePolicy)
        self.FPick.setMaximumSize(QtCore.QSize(112, 34))
        self.FPick.setObjectName("FPick")
        self.RightUp3.addWidget(self.FPick)
        self.verticalLayout_8.addLayout(self.RightUp3)
        self.RightUp4 = QtWidgets.QHBoxLayout()
        self.RightUp4.setContentsMargins(15, 5, 15, 5)
        self.RightUp4.setObjectName("RightUp4")
        self.ETip = QtWidgets.QLabel(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ETip.sizePolicy().hasHeightForWidth())
        self.ETip.setSizePolicy(sizePolicy)
        self.ETip.setMinimumSize(QtCore.QSize(0, 40))
        self.ETip.setObjectName("ETip")
        self.RightUp4.addWidget(self.ETip)
        self.EPath = QtWidgets.QLineEdit(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EPath.sizePolicy().hasHeightForWidth())
        self.EPath.setSizePolicy(sizePolicy)
        self.EPath.setObjectName("EPath")
        self.RightUp4.addWidget(self.EPath)
        self.EPick = QtWidgets.QPushButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EPick.sizePolicy().hasHeightForWidth())
        self.EPick.setSizePolicy(sizePolicy)
        self.EPick.setMaximumSize(QtCore.QSize(112, 34))
        self.EPick.setObjectName("EPick")
        self.RightUp4.addWidget(self.EPick)
        self.verticalLayout_8.addLayout(self.RightUp4)
        self.RightUp5 = QtWidgets.QHBoxLayout()
        self.RightUp5.setContentsMargins(15, 5, 15, 5)
        self.RightUp5.setObjectName("RightUp5")
        self.FWorkTipR = QtWidgets.QLabel(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWorkTipR.sizePolicy().hasHeightForWidth())
        self.FWorkTipR.setSizePolicy(sizePolicy)
        self.FWorkTipR.setMinimumSize(QtCore.QSize(0, 40))
        self.FWorkTipR.setObjectName("FWorkTipR")
        self.RightUp5.addWidget(self.FWorkTipR)
        self.FWorkPathR = QtWidgets.QLineEdit(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWorkPathR.sizePolicy().hasHeightForWidth())
        self.FWorkPathR.setSizePolicy(sizePolicy)
        self.FWorkPathR.setObjectName("FWorkPathR")
        self.RightUp5.addWidget(self.FWorkPathR)
        self.FWorkPick = QtWidgets.QPushButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWorkPick.sizePolicy().hasHeightForWidth())
        self.FWorkPick.setSizePolicy(sizePolicy)
        self.FWorkPick.setMaximumSize(QtCore.QSize(112, 34))
        self.FWorkPick.setObjectName("FWorkPick")
        self.RightUp5.addWidget(self.FWorkPick)
        self.verticalLayout_8.addLayout(self.RightUp5)
        self.LineR = QtWidgets.QFrame(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineR.sizePolicy().hasHeightForWidth())
        self.LineR.setSizePolicy(sizePolicy)
        self.LineR.setFrameShape(QtWidgets.QFrame.HLine)
        self.LineR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineR.setObjectName("LineR")
        self.verticalLayout_8.addWidget(self.LineR)
        self.RightUp6 = QtWidgets.QHBoxLayout()
        self.RightUp6.setContentsMargins(10, -1, -1, -1)
        self.RightUp6.setObjectName("RightUp6")
        self.CallJMCT = QtWidgets.QRadioButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CallJMCT.sizePolicy().hasHeightForWidth())
        self.CallJMCT.setSizePolicy(sizePolicy)
        self.CallJMCT.setMinimumSize(QtCore.QSize(0, 40))
        self.CallJMCT.setChecked(False)
        self.CallJMCT.setObjectName("CallJMCT")
        self.RightUp6.addWidget(self.CallJMCT)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.RightUp6.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.RightUp6)
        self.RightUp7 = QtWidgets.QHBoxLayout()
        self.RightUp7.setContentsMargins(15, 5, 15, 5)
        self.RightUp7.setObjectName("RightUp7")
        self.JInTip = QtWidgets.QLabel(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JInTip.sizePolicy().hasHeightForWidth())
        self.JInTip.setSizePolicy(sizePolicy)
        self.JInTip.setMinimumSize(QtCore.QSize(0, 40))
        self.JInTip.setObjectName("JInTip")
        self.RightUp7.addWidget(self.JInTip)
        self.JInPath = QtWidgets.QLineEdit(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JInPath.sizePolicy().hasHeightForWidth())
        self.JInPath.setSizePolicy(sizePolicy)
        self.JInPath.setObjectName("JInPath")
        self.RightUp7.addWidget(self.JInPath)
        self.JInPick = QtWidgets.QPushButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JInPick.sizePolicy().hasHeightForWidth())
        self.JInPick.setSizePolicy(sizePolicy)
        self.JInPick.setMaximumSize(QtCore.QSize(112, 34))
        self.JInPick.setObjectName("JInPick")
        self.RightUp7.addWidget(self.JInPick)
        self.verticalLayout_8.addLayout(self.RightUp7)
        self.StatusR = QtWidgets.QTextBrowser(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusR.sizePolicy().hasHeightForWidth())
        self.StatusR.setSizePolicy(sizePolicy)
        self.StatusR.setMinimumSize(QtCore.QSize(0, 0))
        self.StatusR.setObjectName("StatusR")
        self.verticalLayout_8.addWidget(self.StatusR)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(70, 5, 70, 5)
        self.horizontalLayout_21.setSpacing(70)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.QuitR = QtWidgets.QPushButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuitR.sizePolicy().hasHeightForWidth())
        self.QuitR.setSizePolicy(sizePolicy)
        self.QuitR.setMaximumSize(QtCore.QSize(112, 34))
        self.QuitR.setObjectName("QuitR")
        self.horizontalLayout_21.addWidget(self.QuitR)
        self.ResetR = QtWidgets.QPushButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetR.sizePolicy().hasHeightForWidth())
        self.ResetR.setSizePolicy(sizePolicy)
        self.ResetR.setMaximumSize(QtCore.QSize(112, 34))
        self.ResetR.setObjectName("ResetR")
        self.horizontalLayout_21.addWidget(self.ResetR)
        self.StartR = QtWidgets.QPushButton(self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartR.sizePolicy().hasHeightForWidth())
        self.StartR.setSizePolicy(sizePolicy)
        self.StartR.setMaximumSize(QtCore.QSize(112, 34))
        self.StartR.setObjectName("StartR")
        self.horizontalLayout_21.addWidget(self.StartR)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.tabWidget.addTab(self.Call, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.FileEdit.setCurrentIndex(4)
        self.Group.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JFWizard"))
        self.JtoFChose.setText(_translate("MainWindow", "JMCTtoFISP"))
        self.GenTip.setText(_translate("MainWindow", "光子单位时间产额(小数/科学):"))
        self.JOutFIleTipU.setText(_translate("MainWindow", "JMCT输出文件位置:"))
        self.JOutFilePickU.setText(_translate("MainWindow", "浏览"))
        self.GFileTip.setText(_translate("MainWindow", "GDML文件位置:"))
        self.GFilePick.setText(_translate("MainWindow", "浏览"))
        self.FWorkTipU.setText(_translate("MainWindow", "FISPACT工作目录(folder):"))
        self.FWorkPickU.setText(_translate("MainWindow", "浏览"))
        self.FtoJChose.setText(_translate("MainWindow", "FISPtoJMCT"))
        self.RetractTip.setText(_translate("MainWindow", "文本缩进:"))
        self.RetractLen.setCurrentText(_translate("MainWindow", "Space*3"))
        self.RetractLen.setItemText(0, _translate("MainWindow", "Space*3"))
        self.RetractLen.setItemText(1, _translate("MainWindow", "Space*2"))
        self.RetractLen.setItemText(2, _translate("MainWindow", "Space*4"))
        self.RetractLen.setItemText(3, _translate("MainWindow", "Tab"))
        self.MaxFlagTip.setText(_translate("MainWindow", "光谱无穷大等效值:"))
        self.MaxFlag.setText(_translate("MainWindow", "20.0"))
        self.JModelTip.setText(_translate("MainWindow", "JMCT模板文件位置:"))
        self.JModelPick.setText(_translate("MainWindow", "浏览"))
        self.FWorkTipD.setText(_translate("MainWindow", "FISPACT工作目录:"))
        self.FWorkPickD.setText(_translate("MainWindow", "浏览"))
        self.JOutFIleTipD.setText(_translate("MainWindow", "JMCT输出文件位置:"))
        self.JOutFilePickD.setText(_translate("MainWindow", "浏览"))
        self.LoadFile.setText(_translate("MainWindow", "导入模板文件"))
        self.CFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MONITOR 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">COLLAPSE 175</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FISPACT</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* {title}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* END OF RUN</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Collapx), _translate("MainWindow", "collapx.i"))
        self.AFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MONITOR 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SPEK</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ENFA</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* {title}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TAPA</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FISPACT</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* WRITE DATA TO ARRAY FILE.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* END OF RUN</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Arrayx), _translate("MainWindow", "arrayx.i"))
        self.IFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NOHEAD</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MONITOR 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AINP</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FISPACT</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* {title}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DENSITY {density}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MASS {mass} {elements}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MIND 1.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">HALF</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">GRAPH 2 0 0 1 2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FLUX {flux}</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ATOMS</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LEVEL 100 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TIME 1.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">HALF</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DOSE 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ATOMS</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NOSTABLE</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LEVEL 20 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FLUX 0.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ZERO</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TIME 1.0 HOURS ATOMS</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* END</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/*</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Input), _translate("MainWindow", "input.i"))
        self.PFileEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.Printlib), _translate("MainWindow", "printlib.i"))
        self.FileEdit.setTabText(self.FileEdit.indexOf(self.JMCT), _translate("MainWindow", "jmct"))
        self.Sync.setText(_translate("MainWindow", "复用文件同步"))
        self.GenCall.setText(_translate("MainWindow", "生成调用语句"))
        self.SaveNeu.setText(_translate("MainWindow", "物质信息存留"))
        self.RemainJOut.setText(_translate("MainWindow", "保留JMCT模板"))
        self.QuitL.setText(_translate("MainWindow", "退出"))
        self.ResetL.setText(_translate("MainWindow", "重置"))
        self.StartL.setText(_translate("MainWindow", "开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Transform), _translate("MainWindow", "文件转换"))
        self.CallFISP.setText(_translate("MainWindow", "CallFISP"))
        self.GroupTip.setText(_translate("MainWindow", "能群:"))
        self.Group.setItemText(0, _translate("MainWindow", "69(WIMS)"))
        self.Group.setItemText(1, _translate("MainWindow", "100(GAM-2)"))
        self.Group.setItemText(2, _translate("MainWindow", "172(XMAS)"))
        self.Group.setItemText(3, _translate("MainWindow", "175(VITAMIN-J)"))
        self.Group.setItemText(4, _translate("MainWindow", "211(VITAMIN-J+)"))
        self.Group.setItemText(5, _translate("MainWindow", "315(TRIPOLI)"))
        self.Group.setItemText(6, _translate("MainWindow", "351(TRIPOLI+)"))
        self.WeightTip.setText(_translate("MainWindow", "权函数:"))
        self.Weight.setItemText(0, _translate("MainWindow", "FLA/FLT"))
        self.Weight.setItemText(1, _translate("MainWindow", "FIS"))
        self.Weight.setItemText(2, _translate("MainWindow", "FUS"))
        self.ParticleTip.setText(_translate("MainWindow", "粒子类型:"))
        self.Particle.setItemText(0, _translate("MainWindow", "n"))
        self.Particle.setItemText(1, _translate("MainWindow", "p"))
        self.Particle.setItemText(2, _translate("MainWindow", "d"))
        self.FTip.setText(_translate("MainWindow", "FISPACT执行文件:"))
        self.FPick.setText(_translate("MainWindow", "浏览"))
        self.ETip.setText(_translate("MainWindow", "EAF数据库目录:"))
        self.EPick.setText(_translate("MainWindow", "浏览"))
        self.FWorkTipR.setText(_translate("MainWindow", "FISPACT工作目录:"))
        self.FWorkPick.setText(_translate("MainWindow", "浏览"))
        self.CallJMCT.setText(_translate("MainWindow", "CallJMCT"))
        self.JInTip.setText(_translate("MainWindow", "JMCT输入文件(.in):"))
        self.JInPick.setText(_translate("MainWindow", "浏览"))
        self.QuitR.setText(_translate("MainWindow", "退出"))
        self.ResetR.setText(_translate("MainWindow", "重置"))
        self.StartR.setText(_translate("MainWindow", "开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Call), _translate("MainWindow", "程序调用"))

